using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("CollectionEncounterTooltip.Tests")]
[assembly: InternalsVisibleTo("ItemEnchantPreview.Tests")]
[assembly: InternalsVisibleTo("StartupUploadRunner.Tests")]
[assembly: InternalsVisibleTo("CollectionSourceFiltering.Tests")]
[assembly: InternalsVisibleTo("LiveBuildRecommendations.Tests")]
[assembly: InternalsVisibleTo("RunLoggingModule.Tests")]
[assembly: InternalsVisibleTo("EndOfRunScreenshotGate.Tests")]
[assembly: InternalsVisibleTo("RandomHeroPoolPatchCompatibility.Tests")]
[assembly: InternalsVisibleTo("HistoryPanelFactory.Tests")]
[assembly: InternalsVisibleTo("BundlePipeline.Tests")]
[assembly: InternalsVisibleTo("CombatReplayRecording.Tests")]
[assembly: InternalsVisibleTo("GhostBattleSync.Tests")]
[assembly: InternalsVisibleTo("HistoryPanelRepository.Tests")]
[assembly: InternalsVisibleTo("SupporterCatalogModule.Tests")]
[assembly: InternalsVisibleTo("RuntimeIntegration.Tests")]
