<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <PropertyGroup>
    <ProjectRoot>$(MSBuildThisFileDirectory)../../</ProjectRoot>
    <MacSteamManagedDefault>$(HOME)/Library/Application Support/Steam/steamapps/common/The Bazaar/TheBazaar.app/Contents/Resources/Data/Managed</MacSteamManagedDefault>
    <WinSteamManagedC>C:\Program Files (x86)\Steam\steamapps\common\The Bazaar\TheBazaar_Data\Managed</WinSteamManagedC>
    <WinSteamManagedD>D:\Program Files (x86)\Steam\steamapps\common\The Bazaar\TheBazaar_Data\Managed</WinSteamManagedD>
    <WinSteamManagedE>E:\Program Files (x86)\Steam\steamapps\common\The Bazaar\TheBazaar_Data\Managed</WinSteamManagedE>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ManagedPath)' == '' and Exists('$(WinSteamManagedC)\\Assembly-CSharp.dll')">
    <ManagedPath>$(WinSteamManagedC)</ManagedPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ManagedPath)' == '' and Exists('$(WinSteamManagedD)\\Assembly-CSharp.dll')">
    <ManagedPath>$(WinSteamManagedD)</ManagedPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ManagedPath)' == '' and Exists('$(WinSteamManagedE)\\Assembly-CSharp.dll')">
    <ManagedPath>$(WinSteamManagedE)</ManagedPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ManagedPath)' == '' and Exists('$(MacSteamManagedDefault)/Assembly-CSharp.dll')">
    <ManagedPath>$(MacSteamManagedDefault)</ManagedPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../BazaarPlusPlus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BazaarGameShared">
      <HintPath>$(ManagedPath)/BazaarGameShared.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
