name = "bazaarplusplus-mod-api"
main = "src/index.ts"
compatibility_date = "2026-03-28"
workers_dev = false

[[routes]]
pattern = "mod-api.bazaarplusplus.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "bazaarplusplus-mod-api-db"
database_id = "ed1e45ce-056a-4c49-a742-4044b1ada1e6"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PVP_BATTLE_BUCKET"
bucket_name = "bazaarplusplus-pvp-battles"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = false
invocation_logs = false

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
