name = "bazaarplusplus-mod-api"
main = "src/index.ts"
compatibility_date = "2026-03-28"
workers_dev = false

[[routes]]
pattern = "mod-api.bazaarplusplus.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "bazaarplusplus-mod-api-db"
database_id = "e112f7e4-b1f0-4512-a224-7b1975c17fbf"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PVP_BATTLE_BUCKET"
bucket_name = "bazaarplusplus-pvp-battles"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = false
invocation_logs = false

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
