name = "bazaarplusplus-mod-api"
main = "src/index.ts"
compatibility_date = "2026-03-28"
workers_dev = false

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 0.2

[[routes]]
pattern = "mod-api.bazaarplusplus.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "bazaarplusplus-mod-api-db"
database_id = "5f3e98a7-e6e5-474c-897d-7ef0bf59c14e"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PVP_BATTLE_BUCKET"
bucket_name = "bazaarplusplus-pvp-battles"
