export interface Env {
  DB: D1Database;
  RUN_BUNDLE_BUCKET: R2Bucket;
  REPLAY_DOWNLOAD_SECRET: string;
  GHOST_QUERY_LOOKBACK_DAYS: string;
  RUN_BUNDLE_RETENTION_DAYS: string;
  ALLOW_UNAUTHENTICATED_REPLAY_LINKS?: string;
  ALLOW_UNAUTHENTICATED_REPLAY_DOWNLOADS?: string;
}
