<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/SelectionPoolState.cs"
      Link="Lobby/SelectionPoolState.cs"
    />
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/RandomHeroPool/RandomHeroPoolPreferences.cs"
      Link="RandomHeroPool/RandomHeroPoolPreferences.cs"
    />
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/RandomHeroPool/RandomHeroPoolSelector.cs"
      Link="RandomHeroPool/RandomHeroPoolSelector.cs"
    />
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/RandomHeroPool/RandomHeroPoolState.cs"
      Link="RandomHeroPool/RandomHeroPoolState.cs"
    />
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/RandomHeroPool/RandomHeroPoolStateFactory.cs"
      Link="RandomHeroPool/RandomHeroPoolStateFactory.cs"
    />
    <Compile
      Include="../../src/BazaarPlusPlus/Game/Lobby/RandomHeroPool/RandomHeroPoolNativeController.cs"
      Link="RandomHeroPool/RandomHeroPoolNativeController.cs"
    />
  </ItemGroup>
</Project>
