#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using BazaarGameShared.Domain.Core.Types;
using BazaarPlusPlus.Infrastructure;
using Newtonsoft.Json;

namespace BazaarPlusPlus.Game.CollectionPanel.Encounters;

/// <summary>
/// Loads the curated merchant/trainer catalog (<c>Data/Encounters/merchant-trainer-portraits.json</c>,
/// embedded resource) and exposes lookups keyed by card-template id.
///
/// The catalog is generated by <c>tools/encounter-portraits/build_catalog.py</c> (bazaardb roster
/// cross-referenced with the extractor <c>index.json</c>). We key by template id because display names
/// are not unique to a template id and collide with unrelated encounters — see that script's header.
///
/// Mirrors the embedded-resource load pattern of CardSetPreview.CardSetBuildDataRepository.
/// </summary>
internal static class MerchantTrainerCatalog
{
    private const string LogComponent = "MerchantTrainerCatalog";
    private const string ResourceSuffix = "merchant-trainer-portraits.json";

    private static readonly object SyncRoot = new();
    private static bool _loaded;
    private static IReadOnlyList<MerchantTrainerEntry> _entries =
        Array.Empty<MerchantTrainerEntry>();
    private static IReadOnlyDictionary<Guid, MerchantTrainerEntry> _byTemplateId =
        new Dictionary<Guid, MerchantTrainerEntry>();

    /// <summary>All curated merchant/trainer identities (47 merchants + 23 trainers at patch 14.1).</summary>
    public static IReadOnlyList<MerchantTrainerEntry> Entries
    {
        get
        {
            EnsureLoaded();
            return _entries;
        }
    }

    /// <summary>Resolve a card-template id to its merchant/trainer entry, if it is one.</summary>
    public static bool TryGet(Guid templateId, out MerchantTrainerEntry? entry)
    {
        EnsureLoaded();
        return _byTemplateId.TryGetValue(templateId, out entry);
    }

    /// <summary>Entries that should be shown for <paramref name="hero"/> (empty Heroes == all heroes).</summary>
    public static IEnumerable<MerchantTrainerEntry> ForHero(EHero hero)
    {
        EnsureLoaded();
        foreach (var entry in _entries)
            if (entry.AppliesToHero(hero))
                yield return entry;
    }

    private static void EnsureLoaded()
    {
        if (_loaded)
            return;

        lock (SyncRoot)
        {
            if (_loaded)
                return;

            try
            {
                var json = ReadEmbeddedJson(ResourceSuffix);
                if (!string.IsNullOrEmpty(json))
                {
                    var entries = Build(json!);
                    _entries = entries;
                    _byTemplateId = BuildIndex(entries);
                    BppLog.Info(
                        LogComponent,
                        $"Loaded merchant/trainer catalog entries={entries.Count} templateIds={_byTemplateId.Count}"
                    );
                }
            }
            catch (Exception ex)
            {
                BppLog.Error(LogComponent, "Failed to load merchant/trainer catalog", ex);
            }
            finally
            {
                _loaded = true;
            }
        }
    }

    /// <summary>Parse catalog JSON into runtime entries. Internal for unit testing (no resource I/O).</summary>
    internal static IReadOnlyList<MerchantTrainerEntry> Build(string json)
    {
        var dto = JsonConvert.DeserializeObject<CatalogDto>(json);
        if (dto?.Entries == null)
            return Array.Empty<MerchantTrainerEntry>();

        var result = new List<MerchantTrainerEntry>(dto.Entries.Count);
        foreach (var entry in dto.Entries)
        {
            if (entry == null || string.IsNullOrWhiteSpace(entry.Name))
                continue;

            var templateIds = ParseTemplateIds(entry.TemplateIds);
            if (templateIds.Count == 0)
                continue; // nothing renderable to key on

            var kind = string.Equals(entry.Kind, "Trainer", StringComparison.OrdinalIgnoreCase)
                ? EncounterPortraitKind.Trainer
                : EncounterPortraitKind.Merchant;

            result.Add(
                new MerchantTrainerEntry(
                    entry.Name!,
                    kind,
                    entry.Tier ?? string.Empty,
                    ParseHeroes(entry.Heroes),
                    entry.Description ?? string.Empty,
                    templateIds
                )
            );
        }

        return result;
    }

    /// <summary>Map hero display names to <see cref="EHero"/>. Empty/unknown names are dropped. Internal for testing.</summary>
    internal static IReadOnlyList<EHero> ParseHeroes(IReadOnlyList<string>? names)
    {
        if (names == null || names.Count == 0)
            return Array.Empty<EHero>();

        var heroes = new List<EHero>(names.Count);
        foreach (var name in names)
            if (Enum.TryParse<EHero>(name, ignoreCase: true, out var hero))
                heroes.Add(hero);
        return heroes;
    }

    private static IReadOnlyList<Guid> ParseTemplateIds(IReadOnlyList<string>? ids)
    {
        if (ids == null || ids.Count == 0)
            return Array.Empty<Guid>();

        var result = new List<Guid>(ids.Count);
        foreach (var raw in ids)
            if (Guid.TryParse(raw, out var id) && id != Guid.Empty)
                result.Add(id);
        return result;
    }

    private static IReadOnlyDictionary<Guid, MerchantTrainerEntry> BuildIndex(
        IReadOnlyList<MerchantTrainerEntry> entries
    )
    {
        var map = new Dictionary<Guid, MerchantTrainerEntry>();
        foreach (var entry in entries)
        foreach (var id in entry.TemplateIds)
            map[id] = entry; // template ids are unique across entries by construction
        return map;
    }

    private static string? ReadEmbeddedJson(string suffix)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var resourceName = assembly
            .GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
        if (resourceName == null)
        {
            BppLog.Warn(LogComponent, $"Embedded catalog resource not found suffix={suffix}");
            return null;
        }

        using var stream = assembly.GetManifestResourceStream(resourceName);
        if (stream == null)
            return null;

        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private sealed class CatalogDto
    {
        [JsonProperty("entries")]
        public List<EntryDto>? Entries { get; set; }
    }

    private sealed class EntryDto
    {
        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("kind")]
        public string? Kind { get; set; }

        [JsonProperty("tier")]
        public string? Tier { get; set; }

        [JsonProperty("heroes")]
        public List<string>? Heroes { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("templateIds")]
        public List<string>? TemplateIds { get; set; }
    }
}
