#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using BazaarGameShared.Domain.Core.Types;
using BazaarPlusPlus.Infrastructure;
using Newtonsoft.Json;

namespace BazaarPlusPlus.Game.CollectionPanel.Encounters;

/// <summary>
/// Loads the curated merchant/trainer catalog (<c>Data/Encounters/merchant-trainer-portraits.json</c>,
/// embedded resource) and exposes lookups keyed by card-template id.
///
/// The catalog is generated by <c>tools/encounter-portraits/build_catalog.py</c> (bazaardb roster
/// cross-referenced with the extractor <c>index.json</c>). We key by template id because display names
/// are not unique to a template id and collide with unrelated encounters — see that script's header.
///
/// Mirrors the embedded-resource load pattern of CardSetPreview.CardSetBuildDataRepository.
/// </summary>
internal static class MerchantTrainerCatalog
{
    private const string LogComponent = "MerchantTrainerCatalog";
    private const string ResourceSuffix = "merchant-trainer-portraits.json";

    private static readonly object SyncRoot = new();
    private static bool _loaded;
    private static IReadOnlyList<MerchantTrainerEntry> _entries =
        Array.Empty<MerchantTrainerEntry>();
    private static IReadOnlyDictionary<Guid, MerchantTrainerEntry> _byTemplateId =
        new Dictionary<Guid, MerchantTrainerEntry>();
    private static IReadOnlyDictionary<string, MerchantTrainerEntry> _bySourceKey = new Dictionary<
        string,
        MerchantTrainerEntry
    >(StringComparer.Ordinal);

    /// <summary>All curated merchant/trainer identities (47 merchants + 23 trainers at patch 14.1).</summary>
    public static IReadOnlyList<MerchantTrainerEntry> Entries
    {
        get
        {
            EnsureLoaded();
            return _entries;
        }
    }

    /// <summary>Resolve a card-template id to its merchant/trainer entry, if it is one.</summary>
    public static bool TryGet(Guid templateId, out MerchantTrainerEntry? entry)
    {
        EnsureLoaded();
        return _byTemplateId.TryGetValue(templateId, out entry);
    }

    /// <summary>Resolve a stable source key to its merchant/trainer entry.</summary>
    public static bool TryGetBySourceKey(string sourceKey, out MerchantTrainerEntry? entry)
    {
        EnsureLoaded();
        return _bySourceKey.TryGetValue(sourceKey, out entry);
    }

    /// <summary>Entries that should be shown for <paramref name="hero"/> (empty Heroes == all heroes).</summary>
    public static IEnumerable<MerchantTrainerEntry> ForHero(EHero hero)
    {
        EnsureLoaded();
        foreach (var entry in _entries)
            if (entry.AppliesToHero(hero))
                yield return entry;
    }

    public static IEnumerable<MerchantTrainerEntry> For(
        EncounterPortraitKind kind,
        EHero? selectedHero
    )
    {
        EnsureLoaded();
        return VisibleEntries(_entries, kind, selectedHero);
    }

    private static void EnsureLoaded()
    {
        if (_loaded)
            return;

        lock (SyncRoot)
        {
            if (_loaded)
                return;

            try
            {
                var json = ReadEmbeddedJson(ResourceSuffix);
                if (!string.IsNullOrEmpty(json))
                {
                    var entries = Build(json!);
                    _entries = entries;
                    _byTemplateId = BuildIndex(entries);
                    _bySourceKey = BuildSourceKeyIndex(entries);
                    BppLog.Info(
                        LogComponent,
                        $"Loaded merchant/trainer catalog entries={entries.Count} templateIds={_byTemplateId.Count}"
                    );
                }
            }
            catch (Exception ex)
            {
                BppLog.Error(LogComponent, "Failed to load merchant/trainer catalog", ex);
            }
            finally
            {
                _loaded = true;
            }
        }
    }

    /// <summary>Parse catalog JSON into runtime entries. Internal for unit testing (no resource I/O).</summary>
    internal static IReadOnlyList<MerchantTrainerEntry> Build(string json)
    {
        var dto = JsonConvert.DeserializeObject<CatalogDto>(json);
        if (dto?.Entries == null)
            return Array.Empty<MerchantTrainerEntry>();

        var candidates = new List<EntryBuildCandidate>(dto.Entries.Count);
        foreach (var entry in dto.Entries)
        {
            if (entry == null || string.IsNullOrWhiteSpace(entry.Name))
                continue;

            var templateIds = ParseTemplateIds(entry.TemplateIds);
            if (templateIds.Count == 0)
                continue; // nothing renderable to key on

            var kind = string.Equals(entry.Kind, "Trainer", StringComparison.OrdinalIgnoreCase)
                ? EncounterPortraitKind.Trainer
                : EncounterPortraitKind.Merchant;

            var heroes = ParseHeroes(entry.Heroes);
            candidates.Add(
                new EntryBuildCandidate(
                    BuildBaseSourceKey(kind, entry.Name!, entry.Tier ?? string.Empty, heroes),
                    entry.Name!,
                    kind,
                    entry.Tier ?? string.Empty,
                    heroes,
                    entry.Description ?? string.Empty,
                    templateIds
                )
            );
        }

        var baseKeyCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var candidate in candidates)
        {
            baseKeyCounts.TryGetValue(candidate.BaseSourceKey, out var count);
            baseKeyCounts[candidate.BaseSourceKey] = count + 1;
        }

        var usedKeys = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<MerchantTrainerEntry>(candidates.Count);
        foreach (var candidate in candidates)
        {
            var sourceKey =
                baseKeyCounts[candidate.BaseSourceKey] == 1
                    ? candidate.BaseSourceKey
                    : $"{candidate.BaseSourceKey}:{BuildTemplateIdsFingerprint(candidate.TemplateIds)}";
            if (!usedKeys.Add(sourceKey))
                throw new InvalidOperationException(
                    $"Duplicate merchant/trainer source key: {sourceKey}"
                );

            result.Add(
                new MerchantTrainerEntry(
                    sourceKey,
                    candidate.Name,
                    candidate.Kind,
                    candidate.Tier,
                    candidate.Heroes,
                    candidate.Description,
                    candidate.TemplateIds
                )
            );
        }
        return result;
    }

    internal static IEnumerable<MerchantTrainerEntry> VisibleEntries(
        IReadOnlyList<MerchantTrainerEntry> entries,
        EncounterPortraitKind kind,
        EHero? selectedHero
    )
    {
        foreach (var entry in entries)
        {
            if (entry.Kind != kind)
                continue;
            if (selectedHero.HasValue && !entry.AppliesToHero(selectedHero.Value))
                continue;
            yield return entry;
        }
    }

    /// <summary>Map hero display names to <see cref="EHero"/>. Empty/unknown names are dropped. Internal for testing.</summary>
    internal static IReadOnlyList<EHero> ParseHeroes(IReadOnlyList<string>? names)
    {
        if (names == null || names.Count == 0)
            return Array.Empty<EHero>();

        var heroes = new List<EHero>(names.Count);
        foreach (var name in names)
            if (Enum.TryParse<EHero>(name, ignoreCase: true, out var hero))
                heroes.Add(hero);
        return heroes;
    }

    private static IReadOnlyList<Guid> ParseTemplateIds(IReadOnlyList<string>? ids)
    {
        if (ids == null || ids.Count == 0)
            return Array.Empty<Guid>();

        var result = new List<Guid>(ids.Count);
        foreach (var raw in ids)
            if (Guid.TryParse(raw, out var id) && id != Guid.Empty)
                result.Add(id);
        return result;
    }

    private static IReadOnlyDictionary<Guid, MerchantTrainerEntry> BuildIndex(
        IReadOnlyList<MerchantTrainerEntry> entries
    )
    {
        var map = new Dictionary<Guid, MerchantTrainerEntry>();
        foreach (var entry in entries)
        foreach (var id in entry.TemplateIds)
            map[id] = entry; // template ids are unique across entries by construction
        return map;
    }

    private static IReadOnlyDictionary<string, MerchantTrainerEntry> BuildSourceKeyIndex(
        IReadOnlyList<MerchantTrainerEntry> entries
    )
    {
        var map = new Dictionary<string, MerchantTrainerEntry>(StringComparer.Ordinal);
        foreach (var entry in entries)
            map[entry.SourceKey] = entry;
        return map;
    }

    private static string BuildBaseSourceKey(
        EncounterPortraitKind kind,
        string name,
        string tier,
        IReadOnlyList<EHero> heroes
    )
    {
        var heroKey =
            heroes.Count == 0
                ? "global"
                : string.Join(
                    "+",
                    heroes
                        .Select(hero => hero.ToString())
                        .OrderBy(value => value, StringComparer.Ordinal)
                );
        return string.Join(
            ":",
            kind.ToString().ToLowerInvariant(),
            Slug(name),
            Slug(tier),
            Slug(heroKey)
        );
    }

    private static string BuildTemplateIdsFingerprint(IReadOnlyList<Guid> templateIds) =>
        string.Join(
            "-",
            templateIds.OrderBy(id => id).Select(id => id.ToString("N").Substring(0, 12))
        );

    private static string Slug(string value)
    {
        var chars = new List<char>(value.Length);
        var lastWasSeparator = false;
        foreach (var raw in value.Trim().ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(raw))
            {
                chars.Add(raw);
                lastWasSeparator = false;
                continue;
            }

            if (!lastWasSeparator && chars.Count > 0)
            {
                chars.Add('-');
                lastWasSeparator = true;
            }
        }

        if (chars.Count > 0 && chars[chars.Count - 1] == '-')
            chars.RemoveAt(chars.Count - 1);
        return chars.Count == 0 ? "unknown" : new string(chars.ToArray());
    }

    private static string? ReadEmbeddedJson(string suffix)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var resourceName = assembly
            .GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
        if (resourceName == null)
        {
            BppLog.Warn(LogComponent, $"Embedded catalog resource not found suffix={suffix}");
            return null;
        }

        using var stream = assembly.GetManifestResourceStream(resourceName);
        if (stream == null)
            return null;

        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private sealed class CatalogDto
    {
        [JsonProperty("entries")]
        public List<EntryDto>? Entries { get; set; }
    }

    private sealed class EntryDto
    {
        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("kind")]
        public string? Kind { get; set; }

        [JsonProperty("tier")]
        public string? Tier { get; set; }

        [JsonProperty("heroes")]
        public List<string>? Heroes { get; set; }

        [JsonProperty("description")]
        public string? Description { get; set; }

        [JsonProperty("templateIds")]
        public List<string>? TemplateIds { get; set; }
    }

    private sealed class EntryBuildCandidate
    {
        public EntryBuildCandidate(
            string baseSourceKey,
            string name,
            EncounterPortraitKind kind,
            string tier,
            IReadOnlyList<EHero> heroes,
            string description,
            IReadOnlyList<Guid> templateIds
        )
        {
            BaseSourceKey = baseSourceKey;
            Name = name;
            Kind = kind;
            Tier = tier;
            Heroes = heroes;
            Description = description;
            TemplateIds = templateIds;
        }

        public string BaseSourceKey { get; }

        public string Name { get; }

        public EncounterPortraitKind Kind { get; }

        public string Tier { get; }

        public IReadOnlyList<EHero> Heroes { get; }

        public string Description { get; }

        public IReadOnlyList<Guid> TemplateIds { get; }
    }
}
