import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { resolve } from "node:path";
import { defineConfig } from "vite";

const frontendDirectory = __dirname;

export default defineConfig({
  resolve: {
    alias: {
      "@": resolve(frontendDirectory, "src"),
    },
  },
  define: {
    "process.env.NODE_ENV": JSON.stringify("production"),
  },
  plugins: [react(), tailwindcss()],
  build: {
    cssCodeSplit: false,
    emptyOutDir: true,
    lib: {
      entry: resolve(frontendDirectory, "src/main.tsx"),
      formats: ["iife"],
      name: "BazaarPlusPlusCombatReportViewer",
    },
    minify: "esbuild",
    outDir: resolve(frontendDirectory, "dist"),
    reportCompressedSize: false,
    rollupOptions: {
      output: {
        assetFileNames: (asset) =>
          asset.names.some((name) => name.endsWith(".css"))
            ? "viewer.css"
            : "[name][extname]",
        banner:
          "/* Generated by CombatReplayReport/frontend/build.mjs. Do not edit directly. */",
        entryFileNames: "viewer.js",
        inlineDynamicImports: true,
      },
    },
    sourcemap: false,
    target: "es2021",
  },
});
